config/routes.rb
Rails.application.routes.draw do
  devise_for :agendify_users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign_up'}

  root 'application#index'
  get 'calendar'=> 'events#calendar'
  get 'contacts'=>'contacts#index'
  post 'post_event'=>'events#post_event'
  post 'post_contact'=>'contacts#post_contact'

  get 'events' => 'events#get_events'
  

end

app/models/agendify_user.rb
class AgendifyUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
  has_many :events
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :agendify_user
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :agendify_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    if agendify_user_signed_in?
      redirect_to '/calendar'
    else
      @message = "Home Page"
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ActionController::Base
	before_action :authenticate_agendify_user!

	# This function is executed when the url: localhost:3000/contacts is entered.
	# It then serves up the contacts page and displays the current user's contacts
	def index
		@page_title = "My Contacts"
		@contacts = current_agendify_user.contacts
	end

	# This function receives contact information from the user
	# It then saves the contact to the DB and pushes it to the user's contacts
	def post_contact
		contact = Contact.new
		contact.first_name = params[:first_name]
		contact.last_name = params[:last_name]
		contact.phone_number = params[:phone_number]
		contact.email = params[:email]
		contact.save
		current_agendify_user.contacts.push(contact)
		current_agendify_user.save
		redirect_to root_path
	end

end

app/controllers/events_controller.rb
require 'date'
class EventsController < ActionController::Base
	before_action :authenticate_agendify_user!

	def calendar
		@message = "calendar"
		@events = current_agendify_user.events.order('start asc')
	end

	def post_event
		event = Event.new
		event.title = params[:title]
		event.start = params[:start]
		event.event_notes = params[:notes]
		event.event_color = params[:backgroundColor]
		event.save
		current_agendify_user.events.push(event)
		current_agendify_user.save
		redirect_to root_path
	end

	def get_events
		@events = current_agendify_user.events
		render json: @events
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/contactdirectory.html.erb
<script type="text/javascript">
	$(document).ready(function(){

		$('#contact_adder').click(function(){

			var contact_object = {
				first_name: $('#first_name').val(),
				last_name:$('#last_name').val(),
				email: $('#email').val(),
				phone_number: $('#phone_number').val()
			};

        	// Send my event to db
        	$.ajax({
        		type: "POST",
        		url: "post_contact",
        		data: contact_object
        	});

        	$('#myModal').modal('hide');
		});

	});
</script>


<div class="row">
	<div class="contact-adder col-md-12">
		<button class="btn btn-primary" id="contact-pop-up" data-toggle="modal" data-target="#myModal">
		<i class="fa fa-user"></i> Add A New Contact </button>
	</div>
	<div class="col-md-12 contact-list">
		<% if @contacts.size > 0 %>
			<table class="table">
				<% @contacts.each do |contact| %>
					<tr>
						<th><h4><%= contact.last_name %>, <%= contact.first_name %></h4></th>
						<td><a>Phone: <%=contact.phone_number %></a></td>
						<td><a>Email: <%=contact.email %></a></td>
					</tr>
				<% end %>
			</table>
		<%else%>
			<h3> Looks like you have not added any contacts yet! </h3>
		<%end%>
	</div>
</div>

<div id="myModal" class="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<div class="contact-header">
					<h4 class="modal-title"> Create A New Contact </h4>
				</div>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="First Name" name="first_name" id="first_name"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="Last Name" name="last_name" id="last_name"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="email" class="form-control" placeholder="Email" name="email" id="email"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="Phone Number" name="phone_number" id="phone_number"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<button id="contact_adder" class="btn btn-primary">Add to contacts</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/application/index.html.erb
<div class="row">
	<div class="banner col-md-8 col-md-offset-2">
		<h2 id="main-header">Agendify</h2>
		<h5 id="main-sub-header">Bringing your agenda to the web</h5>
	</div>
</div>
<div class="descriptive-panel panel panel-default">
	<div class="descriptive-row row">
		<div class="col-md-6">
			<div class="descriptive panel-body">
				<h4>About</h4>
				<p> Agendify is a free web based application that helps students manage their agendas </p>
			</div>
		</div>
		<div class="col-md-6">
			<div class="descriptive panel-body">
				<h4> Features </h4>
				<p>
					Agendify allows students to:
					<ul>
						<li class="fa fa-calendar"> Plan & organize your calendar </li>
						<li class="fa fa-pencil-square-o"> Keep track of your homeworks, exams, and events </li>
						<li class="fa fa-users"> Organize and manage your contacts </li>
					</ul>
				</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="footer-content col-md-5">
  	<span class="footer-signature">&copy;Vidya Gopal 2014/15</span>
  </div>
  <div class="footer-content col-md-5">
  	<span class="footer-signature">Powered by Ruby on Rails <%=image_tag('rails.png', id:'rails-logo')%></span>
  </div>
</nav>
</div>

app/views/contacts/index.html.erb
<script type="text/javascript">
	$(document).ready(function(){

		$('#contact_adder').click(function(){

			var contact_object = {
				first_name: $('#first_name').val(),
				last_name:$('#last_name').val(),
				email: $('#email').val(),
				phone_number: $('#phone_number').val()
			};

        	// Send my event to db
        	$.ajax({
        		type: "POST",
        		url: "post_contact",
        		data: contact_object
        	});

        	$('#myModal').modal('hide');
		});

	});
</script>


<div class="row">
	<div class="contact-adder col-md-12">
		<button class="btn btn-primary" id="contact-pop-up" data-toggle="modal" data-target="#myModal">
		<i class="fa fa-user"></i> Add A New Contact </button>
	</div>
	<div class="col-md-12 contact-list">
		<% if @contacts.size > 0 %>
			<table class="table table-striped">
				<% @contacts.each do |contact| %>
					<tr>
						<th><h4><%= contact.last_name %>, <%= contact.first_name %></h4></th>
						<td><h5>Phone:</h5><a><%=contact.phone_number %></a></td>
						<td><h5>Email:</h5><a><%=contact.email %></a></td>
					</tr>
				<% end %>
			</table>
		<%else%>
			<h3> Looks like you have not added any contacts yet! </h3>
		<%end%>
	</div>
</div>

<div id="myModal" class="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<div class="contact-header">
					<h4 class="modal-title"> Create A New Contact </h4>
				</div>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="First Name" name="first_name" id="first_name"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="Last Name" name="last_name" id="last_name"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="email" class="form-control" placeholder="Email" name="email" id="email"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<input type="text" class="form-control" placeholder="Phone Number" name="phone_number" id="phone_number"/>
						</div>
						<div class="contact-input input-group col-md-12">
							<button id="contact_adder" class="btn btn-primary">Add to contacts</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/events/_event_modal.html.erb
<div id="event_modal" class="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="event-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"> Add A New Event </h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div id="date-message" class="col-md-12">
                           Add an event for <span style="font-weight:bold" id="date-message-header"></span>
                        </div>
                        <div class="event-input input-group col-md-12">
                            <input type="text" class="form-control" placeholder="Event Name" id="event_name"/>
                        </div>
                        <div class="event-input input-group col-md-12">
                            <select class="form-control" id="event_type">
                                <option id="homework" class="label label-success">Homework</option>
                                <option id="tests" class="label label-danger"> Tests </option>
                                <option id="personal" class="label label-primary"> Personal </option>
                                <option id="other" class="label label-warning"> Other </option>
                            </select>
                        </div>
                        <div class="event-input input-group col-md-12">
                            <textarea id="event_notes" rows=5 placeholder=" Enter some notes"></textarea>
                        </div>
                        <div class="event-input input-group col-md-12">
                            <button id="event_adder" class="btn btn-primary" data-btn-name="mybtn">Create Event</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="event_display_modal" class="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="event-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"> Event Details </h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="event-display-input input-group col-md-12">
                            <b>Event Name:</b><span id="event_display_name"></span>
                        </div>
                        <div class="event-display-input input-group col-md-12">
                            <b>Event Date:</b><span id="event_display_date"></span>
                        </div>
                        <div class="event-display-input input-group col-md-12">
                            <b>Event Notes:</b><p id="event_display_notes"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/events/calendar.html.erb
<%= javascript_include_tag 'moment.min.js' %>
<%= javascript_include_tag 'fullcalendar.min.js' %>

<script type="text/javascript">
	$(document).ready(function() {
        var savedEventData = false;

        // Handle data when pop up window is closed
        $('#event_modal').on('hidden.bs.modal', function(event){
            // Check if create event button was clicked
            if(savedEventData){
                // Only save data if create event button was clicked
                var class_name = $('#event_type').find('option:selected').attr('class').split(' ')[1];
                var bg_color = $('.'+class_name).css('background-color');
                var event_object = {
                    title: $('#event_name').val(),
                    start: $('#date-message-header').text(),
                    notes: $('#event_notes').val(),
                    backgroundColor: bg_color
                };
                // Reset pop form values
                $('#event_name').val('').end();
                $('#event_notes').val('').end();
                $('#date-message-header').val('').end();
                $('#calendar').fullCalendar('renderEvent', event_object);

                // Make AJAX call to post data to rails
                $.ajax({
                    type: "POST",
                    url: "post_event",
                    data: event_object
                });
            }
        });

        $('#event_adder').click(function(){
            savedEventData = true;
            $('#event_modal').modal('hide');
        });
                
        $('#calendar').fullCalendar({
            // Load data from rails
            events: function(start, end, timezone, callback){
                $.ajax({
                    url: 'events',
                    dataType: 'json',
                    success: function(event_objs){
                        var res = [];
                        // For each event of this user, render it to the main calendar
                        $.each(event_objs, function(idx, obj){
                            res.push({
                                title: obj.title,
                                start: obj.start,
                                backgroundColor: obj.event_color,
                                notes: obj.event_notes
                            });
                        });
                        callback(res);
                    }
                });
            },

        	// Event handler for day clicks
            dayClick: function(date, jsEvent) {
                $('#event_name').val('').end();
                $('#event_notes').val('').end();
                $('#event_modal').modal('show');
                $('#date-message-header').text(date.format());
        	},

        	// Event handler for event clicks
        	eventClick: function(calEvent, jsEvent, view){
                $('#event_display_modal').modal('show');
                // Set the event name, type, and notes to the pop-up
                $('#event_display_name').text(calEvent.title);
                $('#event_display_date').text(calEvent.start.format('MM-DD-YYYY'));
                $('#event_display_notes').text(calEvent.notes);
        	}
        });

    });
</script>

<div class="row">
    <div class="col-md-7" id='calendar'></div>
    <div class="col-md-3 col-md-offset-1">
        <div class="alert alert-warning supporting_tips">
            <h4><i class="fa fa-lightbulb-o fa-lg"></i> Quick Tip:</h4>
            <span>Click on a day to create a new event </span>
        </div>

        <div class="upcoming-events" style="margin-top:5%">
            <h4> Upcoming Events </h4>
            <table class="table table-striped table-bordered upcoming">
                <% @events.each do |event| %>
                    <tr>
                        <td><%= event.start.strftime("%m/%d/%Y") %></td>
                        <td><span class="label" style="background-color:<%=event.event_color%>"><%= event.title %></span></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

<!-- Render Pop up window -->
<%= render 'event_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://use.edgefonts.net/allan;dhyana.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 navbar-header">
      	<a class="navbar-brand" href="/">Agendify</a>
      </div>
      <div class="col-md-4 navbar-header">
            <ul class="nav navbar-nav">
            <li><%= link_to "My Agenda", "calendar" %></li>
            <li><%= link_to "My Contacts", "contacts" %></li>
            <% if agendify_user_signed_in? %>
              <li><%= link_to "Logout", destroy_agendify_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Log In", 'login' %></li>
              <li><%= link_to "Sign Up", "sign_up", id:"sign_up_btn", class:"btn btn-primary" %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div class="main-content container-fluid">
		<%= yield %>
</div>
</body>
</html>

app/views/layouts/contacts.html.erb
<%= render template: 'layouts/application' %>

app/views/layouts/events.html.erb
<%= render template:'layouts/application' %>